
# PERSONALIZATION
# Site variables
name: The Croquetas Bar Events
og: assets/img/og.png
logo: /assets/img/logo.png
original_repo: https://github.com/TheCroquetasBar/events
description: Find all of The Croquetas Bar's events in one place.
ga: UA-109088240-1
domain: events.croquetasbar.com.au


# Style variables
accent_color: "#39454B"
events_overlay_color: "#98c593;"
background_color: "#FAFAFA"
footer_text_color: "#666666"
events_bg_img: assets/img/bg.jpg

# START THEME 2
# accent_color: "#AA401B"
# events_overlay_color: "#225E50"
# END THEME 2

# START THEME 3
# accent_color: "#FF5722"
# events_overlay_color: "#2697FF"
# END THEME 3

# START THEME 4
# accent_color: "#FF5252"
# events_overlay_color: "#2697FF"
# END THEME 4

# START WINTER THEME
# accent_color: "#165E33" 
# events_overlay_color: "#AA504A"
# END WINTER THEME

# Author variables
author: The Croquetas Bar
author-description: "We are a group of passionate and experienced Chefs and food lovers from Barcelona (Spain) with
                      roots from Andalusia and Basque Country. We cater for every function you may have, weddings,
                      birthdays, afterwork. We can help you make your event a remarkable experience with our authentic
                      mobile Spanish tapas bar."
email: thecroquetasbar@gmail.com

# Social media + community variables
# twitter: thecroquetasbar
fb: thecroquetasbar
# fb-community: thecroquetasbar
# slack-signup: https://slack.thecroquetasbar.org

instagram: thecroquetasbar
linkedin: the-croquetas-bar
github: TheCroquetasBar



# TIMEZONE
# Needs to be string from: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Australia/Perth
# Based on: http://erics-notes.blogspot.com/2013/05/fixing-ics-time-zone.html
ical_timezone: |-
  BEGIN:DAYLIGHT
  TZOFFSETFROM:-0700
  TZOFFSETTO:-0600
  TZNAME:MDT
  DTSTART:19700308T020000
  RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
  END:DAYLIGHT
  BEGIN:STANDARD
  TZOFFSETFROM:-0600
  TZOFFSETTO:-0700
  TZNAME:MST
  DTSTART:19701101T020000
  RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
  END:STANDARD
 
# Internal configuration
sass:
    sass_dir: assets/_sass
    style: compressed
